FROM node:20-alpine AS development

LABEL app.component=backend
LABEL app.stage=development

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

RUN apk add --no-cache \
    postgresql-client \
    redis \
    busybox-extras \
    python3 \
    make \
    g++ \
    wget \
    curl \
    && rm -rf /var/cache/apk/*

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_ENV=development
ENV PRISMA_SCHEMA_PATH=/app/src/libs/infrastructure/database/prisma/schema.prisma

EXPOSE 8088 5555

CMD ["pnpm", "start:dev"]

