/**
 * Centralized error codes for the healthcare application
 * Each error code follows the pattern: [MODULE]_[TYPE]_[SPECIFIC]
 *
 * @enum {string} ErrorCode
 * @description Comprehensive error code enumeration for healthcare application
 * @example
 * ```typescript
 * throw new HealthcareError(ErrorCode.USER_NOT_FOUND, 'User not found');
 * ```
 */
export enum ErrorCode {
  // Authentication & Authorization Errors
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS",
  AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED",
  AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED",
  AUTH_OTP_INVALID = "AUTH_OTP_INVALID",
  AUTH_OTP_EXPIRED = "AUTH_OTP_EXPIRED",
  AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",

  // User Management Errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
  USER_PHONE_ALREADY_EXISTS = "USER_PHONE_ALREADY_EXISTS",
  USER_PROFILE_INCOMPLETE = "USER_PROFILE_INCOMPLETE",
  USER_ROLE_INVALID = "USER_ROLE_INVALID",

  // Clinic Management Errors
  CLINIC_NOT_FOUND = "CLINIC_NOT_FOUND",
  CLINIC_ALREADY_EXISTS = "CLINIC_ALREADY_EXISTS",
  CLINIC_ACCESS_DENIED = "CLINIC_ACCESS_DENIED",
  CLINIC_LICENSE_EXPIRED = "CLINIC_LICENSE_EXPIRED",
  CLINIC_QUOTA_EXCEEDED = "CLINIC_QUOTA_EXCEEDED",

  // Appointment Errors
  APPOINTMENT_NOT_FOUND = "APPOINTMENT_NOT_FOUND",
  APPOINTMENT_ALREADY_EXISTS = "APPOINTMENT_ALREADY_EXISTS",
  APPOINTMENT_CONFLICT = "APPOINTMENT_CONFLICT",
  APPOINTMENT_CANNOT_CANCEL = "APPOINTMENT_CANNOT_CANCEL",
  APPOINTMENT_CANNOT_RESCHEDULE = "APPOINTMENT_CANNOT_RESCHEDULE",
  APPOINTMENT_SLOT_UNAVAILABLE = "APPOINTMENT_SLOT_UNAVAILABLE",
  APPOINTMENT_PAST_DATE = "APPOINTMENT_PAST_DATE",

  // Doctor & Staff Errors
  DOCTOR_NOT_FOUND = "DOCTOR_NOT_FOUND",
  DOCTOR_UNAVAILABLE = "DOCTOR_UNAVAILABLE",
  DOCTOR_ALREADY_ASSIGNED = "DOCTOR_ALREADY_ASSIGNED",
  STAFF_NOT_FOUND = "STAFF_NOT_FOUND",
  STAFF_UNAUTHORIZED = "STAFF_UNAUTHORIZED",

  // Patient Errors
  PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND",
  PATIENT_ALREADY_EXISTS = "PATIENT_ALREADY_EXISTS",
  PATIENT_RECORD_LOCKED = "PATIENT_RECORD_LOCKED",
  PATIENT_CONSENT_REQUIRED = "PATIENT_CONSENT_REQUIRED",

  // Validation Errors
  VALIDATION_REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD",
  VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT",
  VALIDATION_INVALID_EMAIL = "VALIDATION_INVALID_EMAIL",
  VALIDATION_INVALID_PHONE = "VALIDATION_INVALID_PHONE",
  VALIDATION_INVALID_DATE = "VALIDATION_INVALID_DATE",
  VALIDATION_INVALID_TIME = "VALIDATION_INVALID_TIME",
  VALIDATION_INVALID_UUID = "VALIDATION_INVALID_UUID",
  VALIDATION_STRING_TOO_LONG = "VALIDATION_STRING_TOO_LONG",
  VALIDATION_STRING_TOO_SHORT = "VALIDATION_STRING_TOO_SHORT",
  VALIDATION_NUMBER_OUT_OF_RANGE = "VALIDATION_NUMBER_OUT_OF_RANGE",

  // Database Errors
  DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED",
  DATABASE_QUERY_FAILED = "DATABASE_QUERY_FAILED",
  DATABASE_TRANSACTION_FAILED = "DATABASE_TRANSACTION_FAILED",
  DATABASE_CONSTRAINT_VIOLATION = "DATABASE_CONSTRAINT_VIOLATION",
  DATABASE_RECORD_NOT_FOUND = "DATABASE_RECORD_NOT_FOUND",
  DATABASE_DUPLICATE_ENTRY = "DATABASE_DUPLICATE_ENTRY",

  // External Service Errors
  EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE",
  EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT",
  EXTERNAL_SERVICE_INVALID_RESPONSE = "EXTERNAL_SERVICE_INVALID_RESPONSE",
  EMAIL_SERVICE_FAILED = "EMAIL_SERVICE_FAILED",
  SMS_SERVICE_FAILED = "SMS_SERVICE_FAILED",
  WHATSAPP_SERVICE_FAILED = "WHATSAPP_SERVICE_FAILED",
  PAYMENT_SERVICE_FAILED = "PAYMENT_SERVICE_FAILED",

  // File & Media Errors
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  FILE_INVALID_FORMAT = "FILE_INVALID_FORMAT",
  FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED",
  FILE_DOWNLOAD_FAILED = "FILE_DOWNLOAD_FAILED",
  FILE_DELETE_FAILED = "FILE_DELETE_FAILED",

  // Rate Limiting & Security
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  SECURITY_VIOLATION = "SECURITY_VIOLATION",
  SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",
  IP_BLOCKED = "IP_BLOCKED",

  // Business Logic Errors
  BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION",
  WORKFLOW_STATE_INVALID = "WORKFLOW_STATE_INVALID",
  OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED",
  RESOURCE_LOCKED = "RESOURCE_LOCKED",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  CONFIGURATION_ERROR = "CONFIGURATION_ERROR",
  FEATURE_NOT_IMPLEMENTED = "FEATURE_NOT_IMPLEMENTED",
  MAINTENANCE_MODE = "MAINTENANCE_MODE",

  // HIPAA & Compliance Errors
  HIPAA_VIOLATION = "HIPAA_VIOLATION",
  AUDIT_LOG_FAILED = "AUDIT_LOG_FAILED",
  DATA_RETENTION_VIOLATION = "DATA_RETENTION_VIOLATION",
  CONSENT_EXPIRED = "CONSENT_EXPIRED",
  PHI_ACCESS_UNAUTHORIZED = "PHI_ACCESS_UNAUTHORIZED",
}
