/**
 * Default cache TTL in seconds (1 hour)
 */
export const CACHE_TTL = 3600 as const;

/**
 * Redis key prefixes for different data types
 * @constant REDIS_PREFIX
 */
export const REDIS_PREFIX = {
  /** All users cache key */
  USERS_ALL: 'users:all',
  /** Single user cache key */
  USERS_ONE: 'users:one',
  /** All clinics cache key */
  CLINICS_ALL: 'clinics:all',
  /** Single clinic cache key */
  CLINICS_ONE: 'clinics:one',
  /** All doctors cache key */
  DOCTORS_ALL: 'doctors:all',
  /** Single doctor cache key */
  DOCTORS_ONE: 'doctors:one',
  /** All patients cache key */
  PATIENTS_ALL: 'patients:all',
  /** Single patient cache key */
  PATIENTS_ONE: 'patients:one',
  /** All appointments cache key */
  APPOINTMENTS_ALL: 'appointments:all',
  /** Single appointment cache key */
  APPOINTMENTS_ONE: 'appointments:one',
  /** User sessions prefix */
  SESSIONS: 'sessions:',
  /** Authentication attempts prefix */
  AUTH_ATTEMPTS: 'auth:attempts:',
  /** Application logs prefix */
  LOGS: 'logs:',
  /** System events prefix */
  EVENTS: 'events:',
} as const;

/**
 * Type for Redis prefix keys
 */
export type RedisPrefixKey = keyof typeof REDIS_PREFIX;

/**
 * Type for Redis prefix values
 */
export type RedisPrefixValue = (typeof REDIS_PREFIX)[RedisPrefixKey];

/**
 * Default configuration values
 */
export const DEFAULT_CONFIG = {
  /** Default port */
  PORT: 8088,
  /** Default API prefix */
  API_PREFIX: '/api/v1',
  /** Default environment */
  ENVIRONMENT: 'development' as const,
  /** Default JWT expiration */
  JWT_EXPIRATION: '24h',
  /** Default Redis TTL */
  REDIS_TTL: 3600,
  /** Default rate limit TTL */
  RATE_LIMIT_TTL: 60,
  /** Default rate limit max requests */
  RATE_LIMIT_MAX: 100,
} as const;

/**
 * Environment variable names - Centralized constants for all environment variables
 * Use these constants instead of hardcoded strings to ensure consistency
 */
export const ENV_VARS = {
  // Application
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  HOST: 'HOST',
  BIND_ADDRESS: 'BIND_ADDRESS',
  API_PREFIX: 'API_PREFIX',
  BASE_URL: 'BASE_URL',
  API_URL: 'API_URL',
  FRONTEND_URL: 'FRONTEND_URL',

  // Database
  DATABASE_URL: 'DATABASE_URL',
  DIRECT_URL: 'DIRECT_URL',
  DATABASE_SQL_INJECTION_PREVENTION_ENABLED: 'DATABASE_SQL_INJECTION_PREVENTION_ENABLED',
  DATABASE_ROW_LEVEL_SECURITY_ENABLED: 'DATABASE_ROW_LEVEL_SECURITY_ENABLED',
  DATABASE_DATA_MASKING_ENABLED: 'DATABASE_DATA_MASKING_ENABLED',
  DATABASE_RATE_LIMITING_ENABLED: 'DATABASE_RATE_LIMITING_ENABLED',
  DATABASE_READ_REPLICAS_ENABLED: 'DATABASE_READ_REPLICAS_ENABLED',
  DATABASE_READ_REPLICAS_STRATEGY: 'DATABASE_READ_REPLICAS_STRATEGY',
  DATABASE_READ_REPLICAS_URLS: 'DATABASE_READ_REPLICAS_URLS',

  // Cache
  CACHE_ENABLED: 'CACHE_ENABLED',
  CACHE_PROVIDER: 'CACHE_PROVIDER',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  REDIS_TTL: 'REDIS_TTL',
  REDIS_PREFIX: 'REDIS_PREFIX',
  REDIS_MAX_MEMORY: 'REDIS_MAX_MEMORY',
  REDIS_POLICY: 'REDIS_POLICY',
  REDIS_ENABLED: 'REDIS_ENABLED',
  DRAGONFLY_ENABLED: 'DRAGONFLY_ENABLED',
  DRAGONFLY_HOST: 'DRAGONFLY_HOST',
  DRAGONFLY_PORT: 'DRAGONFLY_PORT',
  DRAGONFLY_PASSWORD: 'DRAGONFLY_PASSWORD',
  DRAGONFLY_KEY_PREFIX: 'DRAGONFLY_KEY_PREFIX',

  // JWT
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION: 'JWT_EXPIRATION',
  JWT_ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',

  // Logging
  LOG_LEVEL: 'LOG_LEVEL',
  LOG_FORMAT: 'LOG_FORMAT',
  ENABLE_AUDIT_LOGS: 'ENABLE_AUDIT_LOGS',

  // Email
  EMAIL_PROVIDER: 'EMAIL_PROVIDER',
  EMAIL_HOST: 'EMAIL_HOST',
  EMAIL_PORT: 'EMAIL_PORT',
  EMAIL_SECURE: 'EMAIL_SECURE',
  EMAIL_USER: 'EMAIL_USER',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
  EMAIL_FROM: 'EMAIL_FROM',
  MAILTRAP_API_TOKEN: 'MAILTRAP_API_TOKEN',

  // CORS
  CORS_ORIGIN: 'CORS_ORIGIN',
  CORS_CREDENTIALS: 'CORS_CREDENTIALS',
  CORS_METHODS: 'CORS_METHODS',

  // Security
  SECURITY_RATE_LIMIT: 'SECURITY_RATE_LIMIT',
  SECURITY_RATE_LIMIT_MAX: 'SECURITY_RATE_LIMIT_MAX',
  SECURITY_RATE_LIMIT_WINDOW_MS: 'SECURITY_RATE_LIMIT_WINDOW_MS',
  TRUST_PROXY: 'TRUST_PROXY',
  ENABLE_SSL: 'ENABLE_SSL',
  USE_HTTP: 'USE_HTTP',

  // Rate Limiting
  RATE_LIMIT_ENABLED: 'RATE_LIMIT_ENABLED',
  RATE_LIMIT_TTL: 'RATE_LIMIT_TTL',
  RATE_LIMIT_MAX: 'RATE_LIMIT_MAX',
  RATE_LIMIT_WINDOW: 'RATE_LIMIT_WINDOW',
  API_RATE_LIMIT: 'API_RATE_LIMIT',
  AUTH_RATE_LIMIT: 'AUTH_RATE_LIMIT',
  HEAVY_RATE_LIMIT: 'HEAVY_RATE_LIMIT',
  USER_RATE_LIMIT: 'USER_RATE_LIMIT',
  HEALTH_RATE_LIMIT: 'HEALTH_RATE_LIMIT',
  MAX_AUTH_ATTEMPTS: 'MAX_AUTH_ATTEMPTS',
  AUTH_ATTEMPT_WINDOW: 'AUTH_ATTEMPT_WINDOW',
  MAX_CONCURRENT_SESSIONS: 'MAX_CONCURRENT_SESSIONS',
  SESSION_INACTIVITY_THRESHOLD: 'SESSION_INACTIVITY_THRESHOLD',

  // WhatsApp
  WHATSAPP_ENABLED: 'WHATSAPP_ENABLED',
  WHATSAPP_API_URL: 'WHATSAPP_API_URL',
  WHATSAPP_API_KEY: 'WHATSAPP_API_KEY',
  WHATSAPP_PHONE_NUMBER_ID: 'WHATSAPP_PHONE_NUMBER_ID',
  WHATSAPP_BUSINESS_ACCOUNT_ID: 'WHATSAPP_BUSINESS_ACCOUNT_ID',
  WHATSAPP_OTP_TEMPLATE_ID: 'WHATSAPP_OTP_TEMPLATE_ID',
  WHATSAPP_APPOINTMENT_TEMPLATE_ID: 'WHATSAPP_APPOINTMENT_TEMPLATE_ID',
  WHATSAPP_PRESCRIPTION_TEMPLATE_ID: 'WHATSAPP_PRESCRIPTION_TEMPLATE_ID',

  // Prisma
  PRISMA_SCHEMA_PATH: 'PRISMA_SCHEMA_PATH',

  // Docker
  DOCKER_ENV: 'DOCKER_ENV',
  DOCKER_NETWORK: 'DOCKER_NETWORK',

  // Service URLs
  SWAGGER_URL: 'SWAGGER_URL',
  BULL_BOARD_URL: 'BULL_BOARD_URL',
  SOCKET_URL: 'SOCKET_URL',
  REDIS_UI_URL: 'REDIS_UI_URL',
  REDIS_COMMANDER_URL: 'REDIS_COMMANDER_URL',
  LOGGER_URL: 'LOGGER_URL',
  PRISMA_STUDIO_URL: 'PRISMA_STUDIO_URL',
  PGADMIN_URL: 'PGADMIN_URL',
} as const;

/**
 * Type for environment variable names
 */
export type EnvVarName = keyof typeof ENV_VARS;
