/**
 * Type declarations for Prisma-generated EHR entity types
 * These types are generated at runtime by Prisma, but we declare them here
 * to avoid TypeScript errors during compilation in Docker containers
 *
 * This file augments the @prisma/client module to include these types
 * even when they're not yet generated during initial compilation
 */

declare module '@prisma/client' {
  // PrismaClient is the main export from @prisma/client
  // We declare it here to ensure it's available when the module is augmented
  export class PrismaClient {
    constructor(options?: unknown);
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    $transaction<T>(fn: (prisma: PrismaClient) => Promise<T>): Promise<T>;
    [key: string]: unknown;
  }

  // These types are generated by Prisma at runtime
  // We declare them here to satisfy TypeScript during compilation
  export interface MedicalHistory {
    id: string;
    userId: string;
    clinicId: string | null;
    condition: string;
    diagnosis: string | null;
    treatment: string | null;
    doctorId: string | null;
    notes: string | null;
    date: Date;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface LabReport {
    id: string;
    userId: string;
    clinicId: string | null;
    testName: string;
    result: string;
    unit: string | null;
    normalRange: string | null;
    labName: string | null;
    doctorId: string | null;
    notes: string | null;
    date: Date;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface RadiologyReport {
    id: string;
    userId: string;
    clinicId: string | null;
    imageType: string;
    findings: string;
    conclusion: string;
    doctorId: string | null;
    notes: string | null;
    date: Date;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface Vital {
    id: string;
    userId: string;
    clinicId: string | null;
    type: string;
    value: string;
    unit: string | null;
    doctorId: string | null;
    notes: string | null;
    recordedAt: Date;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface Allergy {
    id: string;
    userId: string;
    clinicId: string | null;
    allergen: string;
    severity: string;
    reaction: string;
    diagnosedDate: Date;
    doctorId: string | null;
    notes: string | null;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface Medication {
    id: string;
    userId: string;
    clinicId: string | null;
    name: string;
    dosage: string;
    frequency: string;
    startDate: Date;
    endDate: Date | null;
    prescribedBy: string;
    purpose: string | null;
    sideEffects: string | null;
    doctorId: string | null;
    notes: string | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface Immunization {
    id: string;
    userId: string;
    clinicId: string | null;
    vaccineName: string;
    dateAdministered: Date;
    nextDueDate: Date | null;
    batchNumber: string | null;
    administrator: string | null;
    location: string | null;
    doctorId: string | null;
    notes: string | null;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface FamilyHistory {
    id: string;
    userId: string;
    clinicId: string | null;
    relation: string;
    condition: string;
    diagnosedAge: number | null;
    doctorId: string | null;
    notes: string | null;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface LifestyleAssessment {
    id: string;
    userId: string;
    clinicId: string | null;
    diet: string | null;
    exercise: string | null;
    smoking: string | null;
    alcohol: string | null;
    sleep: string | null;
    stress: string | null;
    occupation: string | null;
    doctorId: string | null;
    notes: string | null;
    createdAt: Date;
    updatedAt: Date;
  }
}
